### ISSUE TITLE
Ontwerpen Component Building Block

### ISSUE THREAD

**Issue by Annevd** [Annevd/component-building-block#1]
# Ontwerpen
## Morphological Chart

Dit is het morphological chart die ik gemaakt hebt voor een contact form:

![Morphological chart](https://github.com/user-attachments/assets/8ac75244-9d04-49ec-a6b8-8c1a4436ff65)

## Morphological Chart Variations

Onderzoek variaties voor jouw component met behulp van een morphological chart. Bespreek je ideeen met een docent voordat je verder gaat.

### V1

![Morphological chart v8](https://github.com/user-attachments/assets/10b81a2c-5ece-43f0-ae5e-6d5436ab9322)

### V2

![Morphological chart v1](https://github.com/user-attachments/assets/ce09e8e6-ba9b-4cb4-8202-e694964076c1)

### V3

![Morphological chart v2](https://github.com/user-attachments/assets/aa7b45ab-46f7-4755-9304-0b3cf29ec878)

### V4

![Morphological chart v3](https://github.com/user-attachments/assets/b20944df-e282-43b9-af2f-4d66869af542)

### V5

![Morphological chart v4](https://github.com/user-attachments/assets/57300f15-9d61-4b39-87c7-7cda00e67f82)

### V6

![Morphological chart v5](https://github.com/user-attachments/assets/a51e6d0d-db17-4292-acc8-1c942d244236)

### V7

![Morphological chart v6](https://github.com/user-attachments/assets/8e1b39a6-d0fc-4ca1-812c-465ab9680f37)

### V8

![Morphological chart v7](https://github.com/user-attachments/assets/c7d06654-c9eb-4923-95a4-7aba207d82b1)

**Comment by Annevd** [comment]
# Ontwerpen

"Als je een GO hebt gekregen werk je verschillende versie van je component uit in Figma. Maak daarna een breakdownschets met de HTML, CSS en JS code voor het component. Schets hoe je responsive, progressive enhancement, performance en toegankelijkheid toepast."

## Figma variaties

Zoals hieronder te zien heb ik gewerkt aan verschillende variaties van mijn ontwerp in Figma. 
**Op volgorde van links naar rechts zie je een:** mobile versie, zero state, focus state, valid input state, invalid input state, successful submission state en een unsuccessful submission state.

Voor de valid input state, invalid input state en de successful submission state heb ik nog een extra variatie eronder ontworpen. Hiervoor heb ik een eigen svg van een plantje gemaakt.

Ik heb vooral aandacht besteed aan V4 en V8 van voorgaande morpological chart.

![design variaties (1)](https://github.com/user-attachments/assets/7ed216a5-0ba4-401d-aafc-1188c70afb66)

### Valid states

Als valid states heb ik 2 opties ontworpen, die ook gecombineerd kunnen worden. De eerste optie is dat wanneer een input field valid is ingevuld, dat het volledige vlak groen wordt. Dit maakt het aan de gebruiker duidelijk dat ze iets goed hebben ingevuld. 
De tweede optie, tevens een toevoeging, is een plantje dat verschijnt en omhoog komt wanneer de gebruiker iets goed heeft ingevuld. Dit maakt het niet alleen nóg duidelijker voor de gebruiker dat ze het goed doen, maar maakt het ook leuker en minder saai om het formulier in te vullen.

### Invalid states

Als invalid state heb ik ontworpen dat het gehele input field rood wordt, met een donkerdere rode outline. Dit valt meteen op en door de rode kleur weet de gebruiker dat er iets niet goed is. 

### Disabled button

Om de gebruiker feedback te geven dat het formulier nog niet klaar is om verstuurd te worden, heb ik de kleur van de button iets grijzer gemaakt dan de originele kleur. Dit geeft de gebruiker het idee dat de button nog niet gebruikt kan worden en dat er dus nog iets in het formulier veranderd moet worden voordat het verstuurd kan worden.

---

## Breakdown

![Frame 10](https://github.com/user-attachments/assets/32ac2d1b-7939-46d7-8f19-23d7226367c8)

---

## Progressive Enhancement

- **Laag 1:** Semantische HTML, form werkt zonder CSS
- **Laag 2:** Basic CSS, visueel aantrekkelijk
- **Laag 3:** Usability, valid states, unvalid states, evt. JS
- **Laag 4:** Pleasurable animtions, zoals een plantje na valid antwoord

## Toegankelijkheid:
- Inputs hebben labels, placeholders, type, value, name en id
- Inputs die ingevuld moeten hebben een ‘required’ attribuut
- Ik gebruik semantische HTML
- Ik zorg voor hoog genoeg contrast

## Performance:
- Ik zorg voor zo compact mogelijke code
- Ik werk met componenten
- Ik hou Javascript minimaal
- Ik gebruik lazy loading op evt. afbeeldingen
- Ik zet vaste hoogte waardes op evt. afbeeldingen om CLS te voorkomen

### [Link naar mijn figma ontwerp](https://www.figma.com/design/Ijnn6Xx2AjMNLBPLyzt1JZ/Component-building-block?node-id=0-1&t=sgvHSwTygdnbq1R1-1)

**Comment by Annevd** [comment]
# Ontwerpen

## Toegankelijkheid

### Contrast inputvelden

De witte inputvelden op de beige achtergrond hebben geen hoog genoeg contrast. Om ervoor te zorgen dat de inputvelden goed zichtbaar blijven zonder het kleurenpalet aan te passen kun je een `border` of `box-shadow` toevoegen. Zo blijven de inputvelden alsnog goed zichtbaar.

**Bijvoorbeeld:**
- Met border:

![image](https://github.com/user-attachments/assets/0d5dc6d6-fdba-45b2-b358-a54a385f34bc)

- Of met box-shadow:

![image](https://github.com/user-attachments/assets/51f53057-a1c2-43a9-b5d5-ef2bee02eea4)

**Beide hebben hiermee een hoog genoeg contrast voor grafische componenten:**

- Border/box-shadow:

<img height=400 src="https://github.com/user-attachments/assets/8c0f3506-e5c9-4d30-ab55-3b44ad4e8150">
<img height=400 src="https://github.com/user-attachments/assets/5d12dd65-e5bc-44e1-87d1-7f863f88898b">

### Contrast placeholder tekst

Ook het contrast van de placeholder-tekst tegenover de witte achtergrond was in eerste instantie niet hoog genoeg.
Door de tekstkleur donkerder te maken, valt het nu wel binnen de richtlijnen.

<img height=400 src="https://github.com/user-attachments/assets/fd22a16f-39c0-4eb6-a724-2de9c1d5573f">

### Contrast disabled submit button

De verzend knop heeft in mijn initiële ontwerp een te laag contrast. Aan de hand van de CCA checker heeft deze nu een hoog genoeg contrast, én is het nog steeds een doffere, lichtere kleur om te laten merken dat je nog niet klaar bent met het formulier.

**Before/after disabled submit button:**

<img width=150 src="https://github.com/user-attachments/assets/1e65b12e-d82a-4611-bd3a-19534d5340c6">
<img width=150 src="https://github.com/user-attachments/assets/ebe57c81-5c2a-4566-8285-f19651f625b3">

**Valid submit button:**

<img width=150 src="https://github.com/user-attachments/assets/60958af2-462d-46af-8546-68b71b01e0ad">

Alles heeft nu een hoog genoeg contrast!

**Comment by Yu-Jing-van-Gerwen** [comment]
Het ontwerp in figma is echt fantastich ik kan zien wat je wilt gaan maken en hoe je dit gaat doen ook snap ik de oplossingsrichting aan de hand van de breakdownschets en je hebt met de Morphological Chart
goed nagedacht welke functionaliteiten er zijn en hoe je wilt die gaan gebruiken voor je form

**Comment by lisavanmansom** [comment]
# Review component building block ontwerp
## Feedback ontwerp

Je gaat heel duidelijk en overzichtelijk te werk, overal staat uitleg bij waar het nodig is. Via de morphological chart zijn alle opties benoemd en verken je verschillende processen, vanuit de morphological chart heb je verschillende variates in Figma uitgewerkt. Door deze 2 stappen heb je een goede opzet van je component ontwerp onderzoek.

Het enige wat ik zou toevoegen aan de morphological chart is een conclusie of bij de titels zeggen wat je gaat uitwerken. Dit is persoonlijke voorkeur, maar ik vind het altijd fijn als ik aan het einde een lijstje heb met wat de opties zijn. Dan is het makkelijker om scannend te lezen, voor jezelf en voor bijvoorbeeld teamgenoten. Maar dit is een voorkeur, dus als je het er niet mee eens bent, doe het vooral dan niet. Op je Figma-variaties heb ik niks aan te merken.

Je breakdown vind ik erg duidelijk, ook is het verkennen van CSS in de breakdown top. Ik doe dat nooit, misschien vanaf nu wel, ben er helemaal door geïnspireerd. Wat ook fijn is, zijn de beschreven processen (performance, PE en accessibilty) bij de breakdown.

Ik weet niet hoe je precies je component heb opgebouwd, of het gehele form een component is, of dat ook de inputs / fieldsets een component zijn? Maar dat zou je nog kunnen aangeven in je breakdown schets.

Na je breakdown schets, verken en test je verder de toegankelijkheid door de kleuren te testen en te kijken of een het toegankelijker is door een schaduw toe te voegen. Ik heb hier niks op aan te merken.

### Wat je goed doet samengevat:
- Je doet eigenlijk vrijwel alles helemaal top, qua overzichtelijk documenteren tot het maken van de Figma ontwerp.

### Verbeterpunten samengevat:
- Geef aan wat de componenten zijn in de breakdown schets;
- Aan het einde van een lange documentatie maak een samenvatten lijstje

## Wat heb ik hiervan zelf geleerd

Door dit te reviewen heb ik zelf geleerd:
- CSS toevoegen aan een breakdown kan nuttig zijn;
- Het overzichtelijk documenteren;

**Comment by Nazneen05x** [comment]
Je hebt een duidelijk en uitgebreid verslag geschreven, het is duidelijk wat je wilt bouwen en ontwerpen. Je hebt een goed gebruiksvriendelijk en PE  ontwerp gemaakt. De verschillende states zijn duidelijk! Goed nagedacht hoe je het wilt aanpakken! Goed gedaan!
