### ISSUE TITLE
meer ruimte toevoegen de tekst staat tegen de zijkant aan

### ISSUE THREAD

**Issue by yujing-student** [Annevd/component-building-block#16]
issue van ons:
@Mossati
@yujing-student
@Jason2426

<hr>

De tekst staat tegen de zijkant aan zet wat padding erbij

![image](https://github.com/user-attachments/assets/edc76293-2879-4fe7-a611-023da8670ffc)

en de rest vonden we er prachtig uit zien op de pagina

**Comment by Annevd** [comment]
Bedankt voor je feedback! Omdat ik weet in welke context dit form gebruikt zou worden, weet ik dat in dit geval padding niet nodig is. Ik verwacht namelijk dat dit form gebruikt gaat worden binnen een section/container, die al de nodige padding heeft. Zo kan dit form in meerdere layouts gebruikt worden.
