### ISSUE TITLE
zijn deze divs nodig

### ISSUE THREAD

**Issue by yujing-student** [Annevd/component-building-block#19]
issue van ons:
@Mossati
@yujing-student
@Jason2426

heb je deze divs nodig? 

https://github.com/Annevd/component-building-block/blob/f7296359ba3c2302b30bccf5e02acd7087d3ed89/src/lib/molecules/Contact-form.svelte#L37-L51

**Comment by Annevd** [comment]
Hey! Yes, deze zijn in dit geval nodig. Ik gebruik deze div als container om mijn plantjes svg te positioneren ten opzichte hiervan.
Dit is omdat je geen `::after` op inputs kan zetten maar wel op een `div`, daarvoor heb ik dus een `div` toegevoegd.
