### ISSUE TITLE
variaties issue en modular scale

### ISSUE THREAD

**Issue by yujing-student** [Annevd/component-building-block#20]
issue van ons:
@Mossati
@yujing-student
@Jason2426

begin met hele grote variaties en ga daarna naar kleine variaties
volgens koop is een grote variatie aanpassing dat er meer ruimte zit tussen de elementen 

hier is een link met documentatie https://lawsofux.com/law-of-proximity/

![image](https://github.com/user-attachments/assets/3ea8b75f-ac11-4024-adae-2f56692b1026)

je kan de marges aanpassen met de modular scale

**Comment by Annevd** [comment]
Ik heb de witruimte tussen de invoervelden verhoogd zodat het duidelijk is welke labels bij welke input fields horen.

![image](https://github.com/user-attachments/assets/a44062ce-2fc1-45ca-abfb-a0c6b792b4e1)

**Comment by Yu-Jing-van-Gerwen** [comment]
<h1>feedback</h1>
Dit heb je perfect gedaan waardoor ik als gebruiker dus direct zie welke label bij welke input field hoort
