### ISSUE TITLE
zet de tekst bij je breakdownschets ner van performance en toegankelijkheid 

### ISSUE THREAD

**Issue by yujing-student** [Annevd/component-building-block#21]
issue van ons:
@Mossati
@yujing-student
@Jason2426

de schets is perfect maar zet je uitleg neer bij de breakdownschets je kan gebruik maken van pages in figma en dan is het bestand minder groot 

![image](https://github.com/user-attachments/assets/59baa2a2-21de-42b9-8230-76d014d4fe33)

![image](https://github.com/user-attachments/assets/b528bbff-dfda-403b-81d3-dfada6d39192)

**Comment by Annevd** [comment]
Gedaan!

![image](https://github.com/user-attachments/assets/a3f46e80-f0cb-4ba1-8026-484868f1cf6d)
