### ISSUE TITLE
SVG in componentenmap?

### ISSUE THREAD

**Issue by TygoWolven** [Annevd/component-building-block#33]
## Wat is het probleem?
Ik zie dat je in je component-library een `svg` hebt neergezet in plaats van een `.svelte` component. Dit is in principe geen probleem als het onder een kopje _assets_ zou staan of _images_, maar in jouw geval staat het in de mappenstructuur van de componenten.

<img width="300" src="https://github.com/user-attachments/assets/1069f277-6a91-46cd-bdec-d17be40e7156">

## Hoe is dit op te lossen?
Je kunt van het bestand een component maken door hem te vernoemen naar _Plant.svelte_. Dan is hij ook in te zetten als herbruikbaar component, en niet als los svg bestand.

**Comment by Annevd** [comment]
Je hebt gelijk! Ga ik doen dankjewel :)
